### ISSUE TITLE
Build script for OLVM fails when compartment-id set in config

### ISSUE THREAD

**Issue by jeliker1** [oracle-devrel/linux-virt-labs#72]
```sh
 ansible-playbook create_instance.yml -i hosts -e "@instances.yml" -e debug_enabled="true"

 . . .
TASK [Print compartment id] **********************************************************************************************************************************
ok: [localhost] => {
    "msg": ""
}
```

…then this condition does not trap the blank/empty  value because it looks only for `undefined`

```yaml
- name: Fail when compartment_id is not defined
  ansible.builtin.fail:
    msg: "Variable for compartment_id is not defined."
  when: my_compartment_id is not defined
```
